### ISSUE TITLE
Keyboard shortcut conflict with Unity

### ISSUE THREAD

**Issue by engelfrost** [timbertson/shellshape#142]
Super+D is used as an alternative setting to show the desktop. I could not change this in Settings > Keyboard, but was able to remove the shortcut by changing it in org.gnome.desktop.wm.keybindings. 

Not sure what you want to do about this, perhaps leave a comment on the website?

**Comment by gfxmonk** [comment]
see #149

**Comment by timbertson** [comment]
fixed a while ago
