### ISSUE TITLE
Padding between tiles not working

### ISSUE THREAD

**Issue by tasmo** [timbertson/shellshape#152]
All tiles are sticked directly to each other without gap.

Debian 8.0, Gnome 3.14.1, shellshape 14

**Comment by beanaroo** [comment]
Same her on Arch, running GNOME 3.16.2 and shellshape 15

**Comment by DoctorJellyface** [comment]
Still a problem here, Arch, GNOME 3.18.2.

**Comment by timbertson** [comment]
Sorry for the slow response on this, Not sure what could have caused this but I'm seeing it too.
