### ISSUE TITLE
Indicator menu items are way too big

### ISSUE THREAD

**Issue by timbertson** [timbertson/shellshape#164]
![shellshape-indicator](https://cloud.githubusercontent.com/assets/14172/12528059/3f2262b8-c1df-11e5-9dbd-1c8bbdc52b72.png)

**Comment by nls1729** [comment]
$ diff extension.js /tmp/extension.js
1545c1545
<                 style_class: 'popup-menu-icon'
---
>                 style_class: 'system-status-icon'
