### ISSUE TITLE
Poor interaction with font resize in gnome-terminal

### ISSUE THREAD

**Issue by inducer** [timbertson/shellshape#168]
If you've got a minute, the gnome-terminal folks are requesting feedback on how they should handle font-size-based terminal resizing:

https://bugzilla.gnome.org/show_bug.cgi?id=762956

Thanks!

**Comment by egmontkob** [comment]
In particular, I believe (without having any experience with any tiling WM) that shellshape should force a certain size to the gnome-terminal window, overriding its geometry hints and size change requests, pretty much as normal WMs do for maximized windows.

**Comment by timbertson** [comment]
Thanks for bringing this up - I may have been a bit late with my response on that bug unfortunately, but maybe it'll help.
