### ISSUE TITLE
Padding surrounding tiles not on left side of monitor

### ISSUE THREAD

**Issue by Lucasvo1** [timbertson/shellshape#175]
I am trying to have some padding surrounding the tiles but whenever I try to put two windows next to each other, only the right window has the padding while the left-side does not have any. Could it have something to do with my dock being on the left side? I did configure it that it hides whenever a window is placed above it. 

I am running Gnome 3.20 btw.

**Comment by timbertson** [comment]
Could you attach a screenshot please? Ideally with a large padding value so it's clear which padding is missing.
