### ISSUE TITLE
Support gnome-shell 3.22

### ISSUE THREAD

**Issue by inducer** [timbertson/shellshape#177]
It seems to start and show the status icon, but it doesn't seem to move any windows (on 3.21.91).

**Comment by zacchiro** [comment]
for me it actually doesn't event start, and it's reported as "not supported" in the tweak tool

**Comment by inducer** [comment]
Well, I hacked `metadata.json`. Forgot to mention that. :-)

**Comment by zacchiro** [comment]
On Wed, Sep 14, 2016 at 07:07:32AM -0700, Andreas Klöckner wrote:
> Well, I hacked `metadata.json`. Forgot to mention that. :-) 

What did you do exactly?

I've tried adding "3.22", and also "3.21" for the avoidance of doubts,
but the shell still refuses to run the extension.

-- 
Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by inducer** [comment]
For the pre-release versions, it seems to want the full version number, e.g. `3.21.91`.

**Comment by zacchiro** [comment]
On Wed, Sep 14, 2016 at 01:16:21PM -0700, Andreas Klöckner wrote:
> For the pre-release versions, it seems to want the full version number, e.g. `3.21.91`.

Ah, amazing, worked like a charm :)

Thanks,
-- 
Stefano Zacchiroli . zack@upsilon.cc . upsilon.cc/zack . . o . . . o . o
Computer Science Professor . CTO Software Heritage . . . . . o . . . o o
Former Debian Project Leader . OSI Board Director  . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by rhofour** [comment]
I think this can be closed now. shellshape installed fine for me with gnome-shell 3.22.1.

**Comment by inducer** [comment]
Yep. The version on `extensions.gnome.org` appears to work. Thanks for getting this fixed!
