### ISSUE TITLE
Feature request: Workspace naming, application locking to workspaces

### ISSUE THREAD

**Issue by hari-rangarajan** [timbertson/shellshape#182]
I'm trying to see if shellshape can support awesomeWM like features.

Can these be done?
*  (API in gnome shell that would allow) workspaces to be named and direct shortcuts to workspaces
* Can window or application name be used to lock windows to specific workspaces.

Thanks

**Comment by timbertson** [comment]
Neither of these features are implemented, and I don't have plans to. However there's nothing shellshape-specific about the functionality as far as I can tell, so if someone does want to work on these I'd recommend making them as a separate gnome-shell extension (so you can use it alongside shellshape, or without).

I don't actually know if there are gnome-shell APIs to achieve what you want, though.

**Comment by hari-rangarajan** [comment]
Thanks. That sounds sensible.
