### ISSUE TITLE
Update for Gnome 3.22 and 3.24?

### ISSUE THREAD

**Issue by jiri-bati-novak** [timbertson/shellshape#189]
Will there be update for Gnome versions 3.22 and 3.24? Is some help needed?

**Comment by rhofour** [comment]
I appear to be running Gnome 3.22 and I haven't experienced any problems. What's not working for you?

Also, note that (last I checked) the build in the Gnome extensions store is out-of-date. I've been running a build from the master branch and I believe this is what's recommended.

**Comment by jiri-bati-novak** [comment]
well, the extension is not showing up in the list of extensions in the tweak-tool, probably something is blocking it in 3.24?

**Comment by jiri-bati-novak** [comment]
right, after installing shelltile from the master branch it already shows itself...
move along, nothing to see here... :)

**Comment by timbertson** [comment]
No, thanks for filing - generally extensions.gnome.org should work (perhaps with some lag), but apparently it still requires explicit support for a shell version before it'll let you install an extension, unlike gnome itself. I've uploaded a new version which adds 3.22 to the list, so it'll eventually get up there.
