### ISSUE TITLE
gup compile: Don't know how to build shellshape/tiling.js.stamp

### ISSUE THREAD

**Issue by Lesik** [timbertson/shellshape#193]
I feel like I'm being really stupid and am overlooking something, but I keep getting this error when running `gup compile`:

```
+ tools/gup compile -j4
gup  compile
gup    Don't know how to build shellshape/tiling.js.stamp
gup  Target `compile` failed with exit status 1
```

**Comment by Lesik** [comment]
I can only reproduce this in [version-0.8.0](https://github.com/timbertson/shellshape/releases/tag/version-0.8.0), master compiles fine.

**Comment by Lesik** [comment]
Please release an update which compiles, as for this extension to be packaged for the official repositories of a distribution, it is recommended to base it off of a stable release, not git master.

**Comment by timbertson** [comment]
Done, apologies I don't have the pushing of tags automated.
