### ISSUE TITLE
Feature Request: add the option of ignoring the geometry of the window.

### ISSUE THREAD

**Issue by unihorn78** [timbertson/shellshape#207]
Add the option of ignoring the geometry of the window. In order that you could maximize the window which do not fit into the screen (more his size))? It is very necessary for situations when the screen resolution is small or large scale interface (for example in Full HD tablets 10 inch need to increase the scale interface). For example, if, at 1920x1080, set the scale (GDK_SCALE (and dconf equivalents)) in 2 (in GNOME you can't put fractional), for example, Ghome Photos stops to get into the screen (and it is impossible to maximize).

**Comment by timbertson** [comment]
I don't understand what you're saying - what are you trying to do, and what is not working?

It sounds like you've got issues with GDK_SCALE (hiDPI) interface. I just tried running gedit with GDK_SCALE=2 and it seems to tile just fine (see screenshot).

Please give me exact instructions on how to reproduce the issue, ideally with a screenshot.

![screenshot from 2017-10-22 16-48-07](https://user-images.githubusercontent.com/14172/31858666-ab070c2e-b740-11e7-92c8-78071ca86aa8.png)

**Comment by unihorn78** [comment]
Full HD Monitor (1920x1080).

GDK_SCALE or org.gnome.desktop.interface scaling-factor = 2.

Run gnome-photos.

Look.

**Comment by unihorn78** [comment]
It (gnome-photos) one (but not only) of the problematic apps.

**Comment by unihorn78** [comment]
![2017-10-22 20-09-48](https://user-images.githubusercontent.com/19252197/31864948-379fdeee-b76f-11e7-84ff-a27560b0d0e1.png)

**Comment by unihorn78** [comment]
![screenshot from 2017-10-22 21-19-55](https://user-images.githubusercontent.com/19252197/31864960-6808a0f2-b76f-11e7-9073-e4c774498e1b.png)

**Comment by unihorn78** [comment]
![screenshot from 2017-10-22 21-29-56](https://user-images.githubusercontent.com/19252197/31865005-333dbd2a-b770-11e7-85f1-12b9e3573e1b.png)

**Comment by unihorn78** [comment]
![screenshot from 2017-10-22 21-28-31](https://user-images.githubusercontent.com/19252197/31865011-451207b8-b770-11e7-9a9b-c584dbb6b269.png)

**Comment by unihorn78** [comment]
![screenshot from 2017-10-22 21-28-56](https://user-images.githubusercontent.com/19252197/31865013-4e0cf65c-b770-11e7-8b75-bd29a3a69518.png)

**Comment by unihorn78** [comment]
Nautilus (with sidebar). Portrait orientation (change display settings).

**Comment by unihorn78** [comment]
The option of ignoring geometry can solve these problems (like this option in kwin) may solve these problems.

**Comment by unihorn78** [comment]
In kwin, for example, forcibly, to set the minimum size of the window, and, with the option of ignoring geometry, problem Windows will properly fit into the screen. Without going beyond it. So as the window Manager will ignore the "abnormal" size which requires a window, and, instead, will use the size of the Windows defined by the window Manager kwin.

**Comment by unihorn78** [comment]
Sorry for the bad English (I use "electrotranslator")

**Comment by timbertson** [comment]
Ah, I think I understand now. Unfortunately, I don't think this can be fixed in shellshape. All shellshape can do is to ask gnome-shell to resize the window, it can't control the window's internal geometry.

This option (like in kwin) would have to be supported in gnome-shell itself, not an extension.
